### ISSUE TITLE
Instalation on OpenSuSE 42.1

### ISSUE THREAD

**Issue by maniat1k** [fusiondirectory/suse-fusiondirectory#1]
Hi! was trying to install fusiondirectory from this link: https://documentation.fusiondirectory.org/en/documentation/admin_installation_sles

But can't finish to install the "php5-pear-CAS" so I mailed to **users@lists.fusiondirectory.org**, from the mail list I get this link: https://integration.fusiondirectory.org/repos/official-releases/rpm/SLES/fusiondirectory-extra/RPMS/

try to install it :

```
fd:~ # rpm -i php5-pear-CAS-1.3.4-1.noarch.rpm
error: Error de dependencias:
        php5-session es necesario por php5-pear-CAS-1.3.4-1.noarch
        php5-spl es necesario por php5-pear-CAS-1.3.4-1.noarch

```

so after that error I lookup to te php repos (3rd party) for opensuse and try to find the "php5-session" and "php5-spl" with no luck
the repo:

`fd:~ # zypper ar http://download.opensuse.org/repositories/server:/php:/extensions/openSUSE_Leap_42.1/ apache-php`

the search:
```
fd:~ # zypper search php5-sesssion
Cargando datos del repositorio...
Leyendo los paquetes instalados...
No se ha encontrado ningún paquete.
fd:~ #

```
```
fd:~ # zypper search php5-spl
Cargando datos del repositorio...
Leyendo los paquetes instalados...

S | Nombre         | Resumen                                    | Tipo     
--+----------------+--------------------------------------------+-----------
  | php5-spl_types | Collection of Special Typehandling Classes | srcpackage
i | php5-spl_types | Collection of Special Typehandling Classes | package  

```
installed "php5-spl_types" instead of php5-spl... does not work eather

```
fd:~ # rpm -i php5-pear-CAS-1.3.4-1.noarch.rpm
error: Error de dependencias:
        php5-session es necesario por php5-pear-CAS-1.3.4-1.noarch
        php5-spl es necesario por php5-pear-CAS-1.3.4-1.noarch

```
tryied to find it with pear

```
fd:~ # pear search session
Retrieving data...0%
..Matched packages, channel pear.php.net:
=======================================
Package            Stable/(Latest) Local
HTTP_Session       0.5.6 (beta)          Object-oriented interface to the session_* family functions
HTTP_Session2      0.7.3 (beta)          PHP5 Session Handler
HTTP_SessionServer 0.5.0 (alpha)         Daemon to store session data that can be accessed via a simple protocol.
fd:~ # pear search spl
Retrieving data...0%
no packages found that match pattern "spl", for channel pear.php.net.
fd:~ #
```

but I'm not sure if witch one in "session" is the correct one. Still no luck with the spl thing.

**Comment by bilbo-the-hobbit** [comment]
hello,

i'm sorry but we don't have any time left to package for Suse, we try to package for SLES 11 SP3 but its missing lots of dependencies when trying to find all the needed libraries

So for now its on hold till we find someone to help us package it

Cheers
